services:
  frontend-react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/
      - /app/node_modules # Prevent overriding node_modules in container by the host
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code/app/backend
    env_file: "./backend/.env"

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama-server
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]