
FROM python:3.11


WORKDIR /code


COPY ./backend/requirements.txt /code/backend/requirements.txt


RUN pip install --no-cache-dir --upgrade -r /code/backend/requirements.txt
RUN pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN pip install torch-geometric


COPY ./backend /code/app/backend
COPY ./qdrant/ /code/app/qdrant


# CMD ["fastapi", "run", "app/main.py", "--port", "80"]  # Default FastAPI dev server - we have uvicorn instead

CMD ["python", "app/backend/main.py"]